---
- name: Validate access to proxy host and port
  wait_for:
    host: "{{ proxy_host }}"
    port: "{{ proxy_port }}"
    delay: 0
    timeout: 3

- name: Validate access to uris with proxy
  uri:
    follow_redirects: all
    validate_certs: false
    timeout: 5
    url: "{{ item }}"
  with_items:
    - https://nginx.org
    - https://docker.io
    - https://example.com
  environment:
    - http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    - https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
      